{% set name = "kats" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kats-{{ version }}.tar.gz
  sha256: bab55112f26d6458dd444696dfe9fd42097effac03813bcef700d87be361149d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.9
  run:
    - attrs >=21.2.0
    - ax-platform
    - convertdate >=2.1.2
    - fbprophet
    - gpytorch
    - holidays >=0.10.2
    - lunarcalendar >=0.0.9
    - matplotlib-base >=2.0.0
    - numba >=0.52.0
    - numpy >=1.15.4
    - pandas >=1.0.4
    - plotly >=4.14.3
    - pymannkendall >=1.4.1
    - pystan >=2.19.1.1
    - python >=3.7,<3.9
    - python-dateutil >=2.8.0
    - scikit-learn >=0.24.2
    - seaborn >=0.11.1
    - setuptools-git >=1.2
    - statsmodels >=0.12.2
    - pytorch
    - tqdm >=4.36.1

test:
  imports:
    - kats
    - kats.detectors

about:
  home: https://github.com/facebookresearch/Kats
  summary: 'kats: kit to analyze time series'
  license: MIT
  license_file: LICENSE
  description: |
    Kats is a toolkit to analyze time series data, a lightweight, easy-to-use,
     and generalizable framework to perform time series analysis. Time series
     analysis is an essential component of Data Science and Engineering work at
     industry, from understanding the key statistics and characteristics,
     detecting regressions and anomalies, to forecasting future trends. Kats
     aims to provide the one-stop shop for time series analysis, including
     detection, forecasting, feature extraction/embedding, multivariate
     analysis, etc.

extra:
  recipe-maintainers:
    - thewchan
